name: Buld and test the Framework
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run_tests:
    name: Run bogus tests
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Run tests (demo)
        run: |
          echo "⚠️ Running some tests #1..."
          echo "⚠️ Running some tests #2..."
          echo "⚠️ Running some tests #3..."
      - name: Trigger tests on examples repos
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/surpher/ci-build-app/dispatches --data '{"event_type": "build_application", "payload": { "sha":"${{ github.sha }}"}"}'
